name: $(Build.SourceBranch)-$(date:yyyyMMdd)$(rev:.r)
# Pipeline triggers on any branch and tag
trigger:
  branches:
    include:
      - main
      - staging
      - qa
  tags:
    include:
      - '*'

# Pipeline will be run on this base image
pool:
  vmImage: 'ubuntu-latest'

# Variables global to this pipeline
# https://docs.microsoft.com/en-us/azure/devops/pipelines/process/variables
variables:
  # Variables defined in Pipelines->Library->Variable Groups in your project in
  # Azure Pipelines
  - group: Hemmeligheter
  # Variables defined here
  - name: fullSha
    value: '$(Build.SourceVersion)'
  - name: imageName
    value: 'eu.gcr.io/prod-bip/ssb/tidsbruk/timeuse-survey-api'
  - name: repoName
    value: 'prod-bip/ssb/tidsbruk/timeuse-survey-api'
  - name: masterTag
    value: 'master'
  - name: 'gcrServiceConnection'
    value: 'gcrServiceConnection-Tidsbruksprosjektet'
  - name: 'sonarCloud'
    value: 'bipSonarCloud-Tidsbruksprosjektet'

  - name: imageTagBeforeVulnerabilityScan
    value: 'imagescan-$(Build.SourceBranchName)-$(fullSha)'
  - name: imageTagAfterVulnerabilityScan
    value: $(Build.SourceBranchName)-$(fullSha)


resources:
  repositories:
    - repository: templates
      type: github
      name: statisticsnorway/azure-pipelines-templates
      ref: refs/tags/1.1.26
#      ref: use-gar-instead-of-nexus-maven
      endpoint: github-Tidsbruksprosjektet

jobs:
  - task: Gradle@3
    displayName: 'Run tests'
    inputs:
      tasks: 'clean check'
      gradleWrapperFile: 'gradlew'
      javaHomeOption: 'JDKVersion'
